config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_sessions
    get 'users/sign_out', to: 'users/sessions#destroy'
  end

  root to: 'home#index'

  resources :users, only: [:show, :edit, :update]

  resources :posts, only: [:new, :create, :index, :destroy]

  get 'search' => 'search#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram-gram</title>
    <meta name="google-site-verification" content="KF7gXyuyzSkasRz9yZZdv2DkeaqYdtJmSdYNa6pMbxk" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
   <nav class="navbar navbar-light bg-light d-flex">
     <div class="container">
       <div class="logo">
         <a class="navbar-brand" href="<%= root_path %>">
           <%= fa_stacked_icon "camera inverse", base: "circle"%>
           Instagram-gram
         </a>
       </div>
       <div class="m-auto">
         <form class="form-inline search-form">
           <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
         </form>
       </div>
       <div class="user-section">
         <a href="<%= root_path %>"><i class="fa fa-home"></i></a>
         <a><i class="fa fa-comment"></i></a>
         <a href="<%= new_post_path %>"><i class="fa fa-plus-square"></i></a>
         <a><i class="fa fa-compass"></i></a>
         <a><i class="fa fa-heart"></i></a>
         <% if user_signed_in? %>
          <a href="<%= user_path(current_user) %>"><i class="fa fa-user"></i></a>
          <!-- <a href="<%= destroy_user_session_path %>"><i class="fa fa-sign-out"></i></a> -->
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <a href="<%= new_user_session_path%>"><i class="fa fa-sign-in"></i></a>
        <% end %>
       </div>
     </div>
   </nav>

   <!--Main content-->
   <main class="container" style="min-height: 500px;">
     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
     <%= yield %>
   </main><br><br><br><br><br><br>

   <!--Footer-->
   <footer class="container footer">
     <nav class="navbar d-flex">
       <ul>
         <li>ABOUT US
         </li>
         <li>SUPPORT</li>
         <li>PRESS</li>
         <li>API</li>
         <li>JOBS</li>
         <li>PRIVACY</li>
         <li>TERMS</li>
         <li>DIRECTORY</li>
         <li>PROFILES</li>
         <li>HASHTAGS</li>
         <li>LANGUAGE</li>
       </ul>
       <p> © 2021 INSTAGRAM-GRAM </p>
     </nav>
   </footer>
 </body>
</html>